version = "3.9.4"
runner.dialect = scala213

maxColumn = 100
align.preset = some

docstrings.style = AsteriskSpace
docstrings.wrap = keep

rewrite.rules = [Imports]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
  ["java\\..*"],
  ["javax\\..*"],
  ["scala\\..*"],
  ["org\\..*"],
  ["com\\..*"]
]

newlines.topLevelStatementBlankLines = [
  {
    regex = "^Import"
    minBreaks = 0
    blanks { before = 1, after = 3 }
  }
]